@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Main.Ronda",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_2011245426 { 
   	label=Cartas
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Carta2011245426[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Carta</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   numero: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   palo: Palo [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Mazo2011245426[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Mazo</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cartas: ArrayList&lt;Carta&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ agarrarCarta(): Carta</TD></TR>
<TR><TD ALIGN="LEFT" >+ cantCartas(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ mezclar()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Pozo2011245426[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Pozo</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   cantidad: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   pozo: Stack&lt;Carta&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ agregarCarta(carta: Carta)</TD></TR>
<TR><TD ALIGN="LEFT" >+ pasarCartas(pozo: Pozo)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2390489 { 
   	label=Main
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Jugador2390489[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Jugador</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   mano: ArrayList&lt;Carta&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   mazo: Mazo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nombre: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   pozo: Pozo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   puntos: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ agregarPozo(carta: Carta)</TD></TR>
<TR><TD ALIGN="LEFT" >+ agregarPuntos(cantidad: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ darCarta(carta: Carta)</TD></TR>
<TR><TD ALIGN="LEFT" >+ darMazo(mazo: Mazo)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getCarta(indice: int): Carta</TD></TR>
<TR><TD ALIGN="LEFT" >+ mostrarCartas()</TD></TR>
<TR><TD ALIGN="LEFT" >+ quitarMazo()</TD></TR>
<TR><TD ALIGN="LEFT" >+ quitarPuntos(cantidad: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Mesa2390489[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Mesa</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cartas: ArrayList&lt;Carta&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ agregarCarta(carta: Carta)</TD></TR>
<TR><TD ALIGN="LEFT" >+ cantCartas(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ mostrarCartas()</TD></TR>
<TR><TD ALIGN="LEFT" >+ tiene(numero: int): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ tomarCarta(seleccionada: int): Carta</TD></TR>
<TR><TD ALIGN="LEFT" >+ verCarta(seleccionada: int): Carta</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Ronda2390489[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Ronda</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   jugadores: ArrayList&lt;Jugador&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   mazo: Mazo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   mesa: Mesa [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- dejarCarta(select: Carta)</TD></TR>
<TR><TD ALIGN="LEFT" >- dejarCarta(jugador: Jugador)</TD></TR>
<TR><TD ALIGN="LEFT" >- elegirCarta(jugador: Jugador): Carta</TD></TR>
<TR><TD ALIGN="LEFT" >+ jugar()</TD></TR>
<TR><TD ALIGN="LEFT" >- ligarCarta(jugador: Jugador)</TD></TR>
<TR><TD ALIGN="LEFT" >- ligarPozo(jugador: Jugador)</TD></TR>
<TR><TD ALIGN="LEFT" >- mostrarMenu()</TD></TR>
<TR><TD ALIGN="LEFT" >- mostrarSituacionPartida(j: Jugador)</TD></TR>
<TR><TD ALIGN="LEFT" >- repartir()</TD></TR>
<TR><TD ALIGN="LEFT" >- soplar(j: Jugador)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Utils2390489[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Utils</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ mostrarTopes(jugadores: ArrayList&lt;Jugador&gt;)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Jugador2390489 -> Carta2011245426[label="mano
[0..*]"];
Jugador2390489 -> Mazo2011245426[label="mazo
[0..1]"];
Jugador2390489 -> Pozo2011245426[label="pozo
[0..1]"];
Mazo2011245426 -> Carta2011245426[label="cartas
[0..*]"];
Mesa2390489 -> Carta2011245426[label="cartas
[0..*]"];
Pozo2011245426 -> Carta2011245426[label="pozo
[0..*]"];
Ronda2390489 -> Jugador2390489[label="jugadores
[0..*]"];
Ronda2390489 -> Mazo2011245426[label="mazo
[0..1]"];
Ronda2390489 -> Mesa2390489[label="mesa
[0..1]"];
    
}
@enduml